### ISSUE TITLE
Negative Zoom Level Display Bug

### ISSUE THREAD

**Issue by ChrisC** [ChiperSoft/Kalendae#121] opened 2014-02-16 21:52 UTC
Currently, on v0.5.0 there's a fairly confusing display bug at negative zoom levels. See attached screengrab at zoom level -1. It appears that the calendar is resizing itself one column too short relative to the rest of the calendar.

![screen shot 2014-02-16 at 1 50 05 pm](https://f.cloud.github.com/assets/58723/2181519/9d487060-9754-11e3-8634-6eb86bd8ffff.png)

**Comment by Florian-R** [comment] 2016-01-13 09:53
FWIW, I cant reproduce this with 0.5.5. I assume this was fixed by ca0a6b105c1f49553e27b87739471f64d12cabfa and this issue can be closed.

**Comment by ChiperSoft** [comment] 2016-01-13 15:56
@Florian-R great to hear, thanks.

**Closed by ChiperSoft** 2016-01-13 15:56 UTC
