### ISSUE TITLE
Kalendae not working for October

### ISSUE THREAD

**Issue by mdedetrich** [ChiperSoft/Kalendae#134] opened 2014-10-04 23:59 UTC
Kalendae appears to be not working for the month of October. I think this may have something to do with daylight savings.

Refer to attached screenshot
![screen shot 2014-10-05 at 10 59 15 am](https://cloud.githubusercontent.com/assets/2337269/4517175/7d55f092-4c22-11e4-86da-7ca8d1cc25e5.png)

**Comment by 3Dgoo** [comment] 2015-06-09 08:02
This issue also happens in Adelaide, Australia. In Adelaide our day light savings time starts the first Sunday of October at 2:00 am. This is the date this problem occurs in the Kalendae calendar each year. 

From my testing this issue occurs in Safari on Mac, iPad, iPhone and the iPod. This problem does not occur in Chrome on these devices, or any device other device.

Here are some examples of the issue on the Kalendae demo page:
![Screenshot image of Kalendae October issue examples](https://cloud.githubusercontent.com/assets/2616373/8053146/0ae398a2-0ecd-11e5-8d91-cfb29eb11d20.png)

In October 2017 our daylight savings day is October 1st. When using a single year view of Kalendae October 2017 is completely skipped. 

Is there any simple fix for this?

**Comment by mdedetrich** [comment] 2015-06-09 13:08
I think the only real to fix this is for Kalendae to completely ignore javascripts `Date` implementation and use a custom one like `Moment` for all of its calculations.

Either that or its doing exceptions for browsers, and that never ends well

**Comment by ChiperSoft** [comment] 2015-06-09 14:05
1. Kalendae *is* using Moment.
2. Moment still uses the JS Date implementation, it just wraps it with a bunch of other mutation functions.

The problem is rooted in a bug in JavaScriptCore's implementation of Date (JSC is the runtime Safari uses). I could try to work around it, but only if I could reproduce it, and I can't.  I'm afraid the only way this bug is ever going to be fixed is if someone who has this problem debugs it and submits a pull-request.

**Comment by 3Dgoo** [comment] 2015-06-09 22:55
If you set your computer timezone to Adelaide - Australia this should recreate the issue.

**Comment by ChiperSoft** [comment] 2015-06-09 23:04
I've tried setting my timezone to every single location every person has reported this problem from, and it still never duplicates for me. I've even tried changing localization settings in OSX and restarting the computer.

**Closed** 2015-06-11 15:45 UTC

**Comment by ChiperSoft** [comment] 2015-06-11 15:57
Just published v0.5.4 with @Turnerj's fix for this (hopefully).

**Comment by mdedetrich** [comment] 2015-06-22 02:09
PS, this video may explain things in better detail

https://www.youtube.com/watch?v=-5wpm-gesOY
